import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.getByRole('option', { name: 'Allergies' }).click();
  await page.getByRole('button', { name: 'Clear' }).click();
  await page.getByTestId('search').click();
  await page.getByTestId('familyDetails').click();
  await page.getByTestId('search').click();
  await page.getByRole('combobox', { name: 'All Categories' }).click();
  await page.getByRole('option', { name: 'Allergies' }).click();
  await page.getByRole('combobox', { name: 'Any Search, Item, Code,' }).click();
  await page.getByRole('combobox', { name: 'Any Search, Item, Code,' }).fill('air');
  await page.getByRole('heading', { name: 'Airflow' }).click();
  await page.getByTestId('Add').click();
  await page.getByTestId('episodes[0].id').click();
  await page.getByRole('button', { name: 'Choose date' }).first().click();
  await page.getByRole('gridcell', { name: '12' }).click();
  await page.getByRole('button', { name: 'Choose date', exact: true }).click();
  await page.getByRole('gridcell', { name: '12' }).click();
  await page.getByTestId('episodes[0].reaction').getByRole('combobox', { name: 'Reaction' }).click();
  await page.getByRole('option', { name: 'Sneezing' }).click();
  await page.getByRole('combobox', { name: 'Reaction Severity' }).click();
  await page.getByRole('option', { name: 'Mild' }).click();
  await page.getByTestId('Allergy Notes').click();
  await page.getByTestId('Allergy Notes').fill('for testing');
  await page.getByTestId('Save').click();
  await page.getByTestId('socialAndFamilyHistory').click();
  await page.getByRole('combobox', { name: 'Highest Educational Level' }).click();
  await page.getByRole('option', { name: 'Post-graduate Qualification' }).click();
  await page.getByRole('combobox', { name: 'Literacy Level Literacy Level' }).click();
  await page.getByRole('option', { name: 'Literate', exact: true }).click();
  await page.getByRole('combobox', { name: 'Annual Income Range($) Annual' }).click();
  await page.getByRole('option', { name: 'More than' }).click();
  await page.locator('[id="1631"]').getByLabel('', { exact: true }).click();
  await page.getByText('Parents', { exact: true }).click();
  await page.locator('#menu-livesWith > .MuiBackdrop-root').click();
  await page.getByRole('textbox', { name: 'notesC355NL000001' }).click();
  await page.getByRole('textbox', { name: 'notesC355NL000001' }).fill('add social history');
  await page.getByTestId('familyDetails').click();
  await page.locator('[id="1621"] #areFamilyMembersAwareOfPatientsHIVStatusC361L45582').click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.locator('[id="1621"] #haveFamilyMembersBeenTestedForHIVC372L45583').click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.locator('[id="1621"] #doYouHaveAnyDependentChildrenC383L45584').click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.getByRole('textbox', { name: 'howManyFathersOfTheChildrenC394L45585' }).click();
  await page.getByRole('textbox', { name: 'howManyFathersOfTheChildrenC394L45585' }).fill('1');
  await page.getByRole('textbox', { name: 'howManyMothersOfTheChildrenC3105L45586' }).click();
  await page.getByRole('textbox', { name: 'howManyMothersOfTheChildrenC3105L45586' }).fill('1');
  await page.getByRole('textbox', { name: 'notesC3116NL000002' }).click();
  await page.getByRole('textbox', { name: 'notesC3116NL000002' }).fill('family details notes');
  await page.getByTestId('historyOfSTIs').click();
  await page.locator('[id="1622"] input[name="otherSTIs"]').check();
  await page.getByRole('textbox', { name: 'notesC3198NL000003' }).click();
  await page.getByRole('textbox', { name: 'notesC3198NL000003' }).fill('testing');
  await page.getByTestId('sexualHistory').click();
  await page.locator('[id="1629"] input[name="sexuallyActive"]').check();
  await page.getByRole('textbox', { name: 'notesC34526NL000004' }).click();
  await page.getByRole('textbox', { name: 'notesC34526NL000004' }).fill('notes');
  await page.getByTestId('sexualPartnerHistory').click();
  await page.locator('[id="1630"] input[name="1LifetimeSP"]').check();
  await page.getByRole('textbox', { name: 'notesC36823NL000005' }).click();
  await page.getByRole('textbox', { name: 'notesC36823NL000005' }).fill('notes');
  await page.getByTestId('hIVTestHistory').click();
  await page.locator('[id="1623"] input[name="inRelationship"]').check();
  await page.getByRole('textbox', { name: 'notesC38214NL000006' }).click();
  await page.getByRole('textbox', { name: 'notesC38214NL000006' }).fill('notes');
  await page.getByTestId('whereTested').click();
  await page.locator('[id="1633"] input[name="bloodBank"]').check();
  await page.getByRole('textbox', { name: 'notesC310826NL000007' }).click();
  await page.getByRole('textbox', { name: 'notesC310826NL000007' }).fill('notes');
  await page.getByTestId('lifestyle').click();
  await page.locator('[id="1626"] #smokingStatusC31251L98766').click();
  await page.getByRole('option', { name: 'Never Smoked' }).click();
  await page.locator('[id="1626"] #substanceAbuseStatusC31262L98767').click();
  await page.getByRole('option', { name: 'No History Substance Abuse' }).click();
  await page.locator('[id="1626"] #everAttendedRehabilitationC31273L98768').click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.getByRole('textbox', { name: 'detailsYearPlaceDiagnosisOutcomeC31284L98769' }).click();
  await page.getByRole('textbox', { name: 'detailsYearPlaceDiagnosisOutcomeC31284L98769' }).fill('test');
  await page.getByRole('textbox', { name: 'notesC31306NL987708' }).click();
  await page.getByRole('textbox', { name: 'notesC31306NL987708' }).fill('notes');
  await page.getByTestId('Next').click();
  await page.getByTestId('End').click();
  await page.getByTestId('Ok').click();
  await page.getByRole('button', { name: 'You are logged in as Manoj' }).click();
  await page.getByText('Logout').click();
});